[project]
name = "rrhh_agents"
version = "0.1.0"
description = "rrhh_agents using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.13"
dependencies = [
    "crewai[tools]>=0.117.1,<1.0.0",
    "gspread",
    "oauth2client"
]

[project.scripts]
rrhh_agents = "rrhh_agents.main:run"
run_crew = "rrhh_agents.main:run"
train = "rrhh_agents.main:train"
replay = "rrhh_agents.main:replay"
test = "rrhh_agents.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
